-- ============================================================
-- BPS_ITEMS POLICIES — REMOVED
--
-- bps_items table has been merged into fnd_items.
-- This file is kept for git history only. It has no effect.
-- ============================================================
