-- ============================================================
-- Recreate om_orders + om_order_lines and populate from legacy ordr / ordr_detail
--
-- Run as one script in Supabase SQL editor or psql.
-- Prerequisites: fnd_tenants, fnd_customers, fnd_items,
--   fn_set_updated_at_ts_only, fn_audit_log — public.ordr and public.ordr_detail present (e.g. dataPump.py)
-- ============================================================

DROP TABLE IF EXISTS om_order_lines CASCADE;
DROP TABLE IF EXISTS om_orders CASCADE;

-- ============================================================
-- om_orders  –  Sales order header (legacy: ordr)
-- Target: Supabase (PostgreSQL 15+)
--
-- order_number    ← ordr.ordr_no as text (unique per tenant)
-- customer_id     ← ordr.cus_id via fnd_customers.legacy_id
--
-- snapshot_data (JSONB) — stable app-facing keys at top level:
--   cus_name   (text, nullable)  ← ordr.cus_name
--   cus_key    (text, nullable)  ← ordr.cus_key
--   route_id   (number, nullable) ← ordr.route_id
--   route_no   (number, nullable) ← ordr.route_stop_no (legacy stop / sequence on route)
--
-- Run after: fnd_customers.sql (functions), fnd_tenants.sql
-- Lines: ordr_detail → om_order_lines (see om_order_lines.sql, seed_om_order_lines.sql)
-- ============================================================

CREATE TABLE IF NOT EXISTS om_orders (
    order_id                BIGINT      GENERATED BY DEFAULT AS IDENTITY (START WITH 400000100001 INCREMENT BY 1) PRIMARY KEY,

    order_number            TEXT        NOT NULL,   -- app-facing, source: ordr.ordr_no

    event_location          TEXT,

    customer_id             BIGINT      REFERENCES fnd_customers(customer_id),  -- source: ordr.cus_id (nullable: legacy rows without cus_id)

    order_date              DATE,                   -- source: ordr.ordr_dt
    order_source            TEXT,                   -- Web, Clerk, Fax, Electronic, SORDER (set by app / later migration)
    delivery_date           DATE        NOT NULL,   -- source: ordr.ordr_prdctn_dt
    delivery_window         TEXT,                   -- source: ordr.ordr_prdctn_cd

    amount                  NUMERIC(14,4) NOT NULL,   -- ordr_amt
    discount_amount         NUMERIC(14,4) NOT NULL,   -- ordr_discount_amt
    quantity                NUMERIC(14,4) NOT NULL,   -- ordr_qty_sold
    tax_amount              NUMERIC(14,4) NOT NULL,   -- ordr_tax_amt

    snapshot_data           JSONB       NOT NULL DEFAULT '{}'::jsonb,

    tenant_id               BIGINT        NOT NULL REFERENCES fnd_tenants(tenant_id) ON DELETE CASCADE,

    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by              BIGINT,
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by              BIGINT,

    UNIQUE (tenant_id, order_number)
);

CREATE INDEX IF NOT EXISTS idx_om_orders_tenant_id
    ON om_orders (tenant_id);

CREATE INDEX IF NOT EXISTS idx_om_orders_customer
    ON om_orders (tenant_id, customer_id);

CREATE INDEX IF NOT EXISTS idx_om_orders_delivery_date
    ON om_orders (tenant_id, delivery_date DESC);

-- TRIGGERS
DROP TRIGGER IF EXISTS trg_om_orders_set_updated ON om_orders;
CREATE TRIGGER trg_om_orders_set_updated
    BEFORE UPDATE ON om_orders
    FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at_ts_only();

DROP TRIGGER IF EXISTS trg_om_orders_audit ON om_orders;
CREATE TRIGGER trg_om_orders_audit
    AFTER INSERT OR UPDATE OR DELETE ON om_orders
    FOR EACH ROW EXECUTE FUNCTION fn_audit_log('order_id');

-- RLS
ALTER TABLE om_orders ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS pol_om_orders_tenant ON om_orders;
CREATE POLICY pol_om_orders_tenant ON om_orders
    USING      (tenant_id = (auth.jwt() -> 'app_metadata' ->> 'tenant_id')::BIGINT)
    WITH CHECK (tenant_id = (auth.jwt() -> 'app_metadata' ->> 'tenant_id')::BIGINT);
-- ============================================================
-- om_order_lines  –  Sales order line items (legacy: ordr_detail)
-- Target: Supabase (PostgreSQL 15+)
--
-- order_id     ← om_orders (match via ordr_detail.ordr_no → order_number)
-- item_id      ← fnd_items via ordr_detail.item_id → legacy_id (nullable if unknown)
--
-- fulfilled_quantity — seed 0; derive from fulfillments in app or batch updates.
--
-- Run after: om_orders.sql, fnd_items.sql (fn_set_updated_at_ts_only, fn_audit_log)
-- ============================================================

CREATE TABLE IF NOT EXISTS om_order_lines (
    order_line_id       BIGINT      GENERATED BY DEFAULT AS IDENTITY (START WITH 400000200001 INCREMENT BY 1) PRIMARY KEY,

    order_id            BIGINT      NOT NULL REFERENCES om_orders(order_id) ON DELETE CASCADE,

    item_id             BIGINT      REFERENCES fnd_items(item_id),

    item_description    TEXT,       -- display text; legacy: ordr_detail.item_desc

    quantity            NUMERIC(14,4) NOT NULL,
    unit_price          NUMERIC(14,4),
    extended_amount     NUMERIC(14,4),
    unit_discount       NUMERIC(14,4) NOT NULL DEFAULT 0,

    fulfilled_quantity  NUMERIC(14,4) NOT NULL DEFAULT 0,

    tenant_id           BIGINT        NOT NULL REFERENCES fnd_tenants(tenant_id) ON DELETE CASCADE,

    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by          BIGINT,
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_by          BIGINT
);

CREATE INDEX IF NOT EXISTS idx_om_order_lines_tenant
    ON om_order_lines (tenant_id);

CREATE INDEX IF NOT EXISTS idx_om_order_lines_order
    ON om_order_lines (tenant_id, order_id);

CREATE INDEX IF NOT EXISTS idx_om_order_lines_item
    ON om_order_lines (tenant_id, item_id);


-- TRIGGERS
DROP TRIGGER IF EXISTS trg_om_order_lines_set_updated ON om_order_lines;
CREATE TRIGGER trg_om_order_lines_set_updated
    BEFORE UPDATE ON om_order_lines
    FOR EACH ROW EXECUTE FUNCTION fn_set_updated_at_ts_only();

DROP TRIGGER IF EXISTS trg_om_order_lines_audit ON om_order_lines;
CREATE TRIGGER trg_om_order_lines_audit
    AFTER INSERT OR UPDATE OR DELETE ON om_order_lines
    FOR EACH ROW EXECUTE FUNCTION fn_audit_log('order_line_id');


-- RLS
ALTER TABLE om_order_lines ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS pol_om_order_lines_tenant ON om_order_lines;
CREATE POLICY pol_om_order_lines_tenant ON om_order_lines
    USING      (tenant_id = (auth.jwt() -> 'app_metadata' ->> 'tenant_id')::BIGINT)
    WITH CHECK (tenant_id = (auth.jwt() -> 'app_metadata' ->> 'tenant_id')::BIGINT);
-- ============================================================
-- POPULATE om_orders FROM LEGACY ORDR TABLE
--
-- Source:  public.ordr, public.customer (for address / invoice flags)
-- Target:  public.om_orders
--
-- snapshot_data keys (stable app-facing names):
--   cus_name, cus_key, route_id, route_no (route_no ← ordr.route_stop_no)
--   shipping address — single line from customer s_* when cus_invc_rqrd = 'Y'
--   Delivery Instructions — cus_dlvr_instr when cus_invc_rqrd = 'Y'
--   billing address — single line from customer b_* when cus_parent_id = cus_id (ACCOUNT)
--
-- Tenant: Alpine Bakery (same pattern as populate_fnd_item_bom.sql)
-- Upsert: ON CONFLICT updates snapshot_data so re-runs refresh JSON from legacy
--
-- Prerequisite: newTables/om_orders.sql applied, fnd_customers populated for cus_id lookup
-- ============================================================

DO $$
DECLARE
    v_tenant_id BIGINT;
    v_inserted    INT;
BEGIN
    SELECT tenant_id INTO v_tenant_id
    FROM fnd_tenants
    WHERE tenant_name = 'Alpine Bakery'
    LIMIT 1;

    IF v_tenant_id IS NULL THEN
        RAISE EXCEPTION 'Tenant "Alpine Bakery" not found in fnd_tenants';
    END IF;

    RAISE NOTICE 'Using tenant_id: %', v_tenant_id;

    INSERT INTO om_orders (
        order_number,
        customer_id,
        order_date,
        delivery_date,
        delivery_window,
        amount,
        discount_amount,
        quantity,
        tax_amount,
        snapshot_data,
        tenant_id
    )
    SELECT
        trim(o.ordr_no::BIGINT::TEXT),
        cus.customer_id,
        o.ordr_dt::DATE,
        COALESCE(o.ordr_prdctn_dt::DATE, o.ordr_dt::DATE, DATE '2000-01-01'),
        NULLIF(trim(o.ordr_prdctn_cd), ''),
        (
            (COALESCE(o.ordr_amt, 0) - COALESCE(o.ordr_discount_amt, 0))
            * COALESCE(o.ordr_qty_sold, 0)
        )::NUMERIC(14,4),
        COALESCE(o.ordr_discount_amt, 0)::NUMERIC(14,4),
        COALESCE(o.ordr_qty_sold, 0)::NUMERIC(14,4),
        COALESCE(o.ordr_tax_amt, 0)::NUMERIC(14,4),
        COALESCE(
            jsonb_strip_nulls(
                jsonb_build_object(
                    'cus_name', o.cus_name,
                    'cus_key', o.cus_key,
                    'route_id', o.route_id::BIGINT,
                    'route_no', o.route_stop_no::INT,
                    'shipping address',
                        CASE WHEN cu.cus_invc_rqrd = 'Y' THEN
                            NULLIF(
                                trim(both ' ,' FROM concat_ws(', ',
                                    NULLIF(trim(COALESCE(cu.s_contact::TEXT, '')), ''),
                                    NULLIF(trim(COALESCE(cu.s_addr1::TEXT, '')), ''),
                                    NULLIF(trim(COALESCE(cu.s_addr2::TEXT, '')), ''),
                                    NULLIF(trim(COALESCE(cu.s_city::TEXT, '')), ''),
                                    NULLIF(trim(COALESCE(cu.s_state::TEXT, '')), ''),
                                    NULLIF(trim(COALESCE(cu.s_zip::TEXT, '')), '')
                                )),
                                ''
                            )
                        END,
                    'Delivery Instructions',
                        CASE WHEN cu.cus_invc_rqrd = 'Y' THEN
                            NULLIF(trim(COALESCE(cu.cus_dlvr_instr::TEXT, '')), '')
                        END,
                    'billing address',
                        CASE
                            WHEN cu.cus_parent_id IS NOT NULL
                             AND cu.cus_id IS NOT NULL
                             AND cu.cus_parent_id::NUMERIC = cu.cus_id::NUMERIC
                            THEN
                                NULLIF(
                                    trim(both ' ,' FROM concat_ws(', ',
                                        NULLIF(trim(COALESCE(cu.b_contact::TEXT, '')), ''),
                                        NULLIF(trim(COALESCE(cu.b_addr1::TEXT, '')), ''),
                                        NULLIF(trim(COALESCE(cu.b_addr2::TEXT, '')), ''),
                                        NULLIF(trim(COALESCE(cu.b_city::TEXT, '')), ''),
                                        NULLIF(trim(COALESCE(cu.b_state::TEXT, '')), ''),
                                        NULLIF(trim(COALESCE(cu.b_zip::TEXT, '')), '')
                                    )),
                                    ''
                                )
                        END
                )
            ),
            '{}'::JSONB
        ),
        v_tenant_id
    FROM ordr o
    LEFT JOIN fnd_customers cus
        ON cus.tenant_id = v_tenant_id
       AND cus.legacy_id = o.cus_id::INT
    LEFT JOIN customer cu
        ON cu.cus_id::NUMERIC = o.cus_id
    ON CONFLICT (tenant_id, order_number) DO UPDATE SET
        snapshot_data = EXCLUDED.snapshot_data;

    GET DIAGNOSTICS v_inserted = ROW_COUNT;
    RAISE NOTICE 'om_orders: % rows affected (insert + snapshot updates)', v_inserted;
END $$;

SELECT COUNT(*) AS om_orders_row_count FROM om_orders;
-- ============================================================
-- POPULATE om_order_lines FROM LEGACY ORDR_DETAIL
--
-- Source:  public.ordr_detail  (SQL Anywhere → PostgreSQL via dataPump.py)
-- Target:  public.om_order_lines
--
-- Synced ordr_detail layout (Alpine / ODBC):
--   ordr_no, item_id, od_qty_sold, od_qty_returned, od_item_cost, od_item_discount,
--   od_item_sliced, od_item_canopy_sliced, od_item_wrapped, od_item_special,
--   od_item_covered, item_desc, item_no
--
-- Only rows with od_qty_sold > 0 (NULL and 0 treated as non-positive).
--
-- Idempotent: deletes existing rows for the tenant, then inserts (order_line_id is surrogate PK).
--
-- Tenant: Alpine Bakery (same pattern as populate_om_orders.sql)
--
-- Prerequisite: newTables/om_order_lines.sql applied, om_orders and fnd_items populated,
--               public.ordr_detail present
-- ============================================================

DO $$
DECLARE
    v_tenant_id BIGINT;
    v_inserted    INT;
    v_deleted     INT;
    v_skipped     INT;
BEGIN
    SELECT tenant_id INTO v_tenant_id
    FROM fnd_tenants
    WHERE tenant_name = 'Alpine Bakery'
    LIMIT 1;

    IF v_tenant_id IS NULL THEN
        RAISE EXCEPTION 'Tenant "Alpine Bakery" not found in fnd_tenants';
    END IF;

    RAISE NOTICE 'Using tenant_id: %', v_tenant_id;

    DELETE FROM om_order_lines WHERE tenant_id = v_tenant_id;
    GET DIAGNOSTICS v_deleted = ROW_COUNT;
    IF v_deleted > 0 THEN
        RAISE NOTICE 'Removed % existing om_order_lines rows for tenant', v_deleted;
    END IF;

    SELECT COUNT(*) INTO v_skipped
    FROM ordr_detail d
    WHERE NOT EXISTS (
        SELECT 1
        FROM om_orders ordr
        WHERE ordr.tenant_id = v_tenant_id
          AND ordr.order_number = trim(d.ordr_no::BIGINT::TEXT)
    );

    IF v_skipped > 0 THEN
        RAISE NOTICE 'ordr_detail rows with no matching om_orders (skipped): %', v_skipped;
    END IF;

    INSERT INTO om_order_lines (
        order_id,
        item_id,
        item_description,
        quantity,
        unit_price,
        extended_amount,
        unit_discount,
        fulfilled_quantity,
        tenant_id
    )
    SELECT
        ordr.order_id,
        itm.item_id,
        NULLIF(trim(both from COALESCE(d.item_desc::TEXT, '')), ''),
        COALESCE(d.od_qty_sold, 0)::NUMERIC(14,4),
        d.od_item_cost::NUMERIC(14,4),
        (
            COALESCE(d.od_qty_sold, 0)::NUMERIC(14,4)
            * (d.od_item_cost::NUMERIC(14,4) - COALESCE(d.od_item_discount, 0)::NUMERIC(14,4))
        ),
        COALESCE(d.od_item_discount, 0)::NUMERIC(14,4),
        0::NUMERIC(14,4),
        v_tenant_id
    FROM ordr_detail d
    INNER JOIN om_orders ordr
        ON ordr.tenant_id = v_tenant_id
       AND ordr.order_number = trim(d.ordr_no::BIGINT::TEXT)
    LEFT JOIN fnd_items itm
        ON itm.tenant_id = v_tenant_id
       AND itm.legacy_id = d.item_id::INT
    WHERE COALESCE(d.od_qty_sold, 0) > 0;

    GET DIAGNOSTICS v_inserted = ROW_COUNT;
    RAISE NOTICE 'om_order_lines: % rows inserted', v_inserted;
END $$;

SELECT COUNT(*) AS om_order_lines_row_count FROM om_order_lines;
