-- ============================================================
-- SEED BPS_ITEMS — REMOVED
--
-- bps_items has been merged into fnd_items.
-- Bakery-specific columns are now seeded directly in seed_fnd_items.sql.
-- This file is kept for git history only. It has no effect.
-- ============================================================
