import type {
  Customer,
  Order,
  Item,
  Invoice,
  Payment,
  TenantDashboardMetrics,
  CustomerDashboardMetrics,
  Product,
} from './types';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Pain de Campagne',
    description: 'Classic French country sourdough with a crisp crust and open crumb. Slow-fermented for 18 hours.',
    category: 'Sourdough',
    imageUrl: 'https://images.pexels.com/photos/1775043/pexels-photo-1775043.jpeg?auto=compress&cs=tinysrgb&w=800',
    price: 8.5,
    isNew: false,
    isFeatured: true,
  },
  {
    id: '2',
    name: 'Croissant au Beurre',
    description: 'Hand-laminated with 72-hour cold fermentation. 27 layers of French AOP butter.',
    category: 'Viennoiserie',
    imageUrl: 'https://images.pexels.com/photos/2135/food-france-morning-breakfast.jpg?auto=compress&cs=tinysrgb&w=800',
    price: 4.25,
    isNew: true,
    isFeatured: true,
  },
  {
    id: '3',
    name: 'Pane di Altamura',
    description: 'Traditional Pugliese semolina bread. DOP certified durum wheat, stone-baked in a wood-fired oven.',
    category: 'Artisan Loaves',
    imageUrl: 'https://images.pexels.com/photos/1568254/pexels-photo-1568254.jpeg?auto=compress&cs=tinysrgb&w=800',
    price: 9.0,
    isNew: false,
    isFeatured: true,
  },
  {
    id: '4',
    name: 'Focaccia Genovese',
    description: 'Classic Ligurian focaccia, dimpled and drenched in extra virgin olive oil with fleur de sel.',
    category: 'Flatbreads',
    imageUrl: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=800',
    price: 6.75,
    isNew: true,
    isFeatured: false,
  },
  {
    id: '5',
    name: 'Baguette Tradition',
    description: 'Baked to French tradition standards. Crisp crust, open crumb, fermented with liquid levain.',
    category: 'Baguettes',
    imageUrl: 'https://images.pexels.com/photos/209206/pexels-photo-209206.jpeg?auto=compress&cs=tinysrgb&w=800',
    price: 3.5,
    isNew: false,
    isFeatured: true,
  },
  {
    id: '6',
    name: 'Brioche Nanterre',
    description: 'Enriched with butter and eggs, feather-light texture. Perfect for fine dining service.',
    category: 'Viennoiserie',
    imageUrl: 'https://images.pexels.com/photos/3892469/pexels-photo-3892469.jpeg?auto=compress&cs=tinysrgb&w=800',
    price: 11.0,
    isNew: true,
    isFeatured: false,
  },
];

export const mockCustomers: Customer[] = [
  {
    id: 'c1',
    name: 'Le Jardin Restaurant',
    email: 'orders@lejardin.com',
    phone: '+1 (555) 234-5678',
    address: '42 Maple Avenue',
    city: 'Portland, OR',
    accountNumber: 'ACC-0042',
    status: 'active',
    balance: 2340.5,
    creditLimit: 10000,
    joinedAt: '2022-03-15',
    deliveryRoute: 'Route A',
  },
  {
    id: 'c2',
    name: 'The Granary Hotel',
    email: 'purchasing@granaryhotel.com',
    phone: '+1 (555) 345-6789',
    address: '8 Harbor Street',
    city: 'Seattle, WA',
    accountNumber: 'ACC-0043',
    status: 'active',
    balance: 5680.0,
    creditLimit: 25000,
    joinedAt: '2021-11-02',
    deliveryRoute: 'Route B',
  },
  {
    id: 'c3',
    name: 'Bistro Vieux Carré',
    email: 'chef@bistrovc.com',
    phone: '+1 (555) 456-7890',
    address: '115 Bourbon Lane',
    city: 'New Orleans, LA',
    accountNumber: 'ACC-0044',
    status: 'active',
    balance: 890.25,
    creditLimit: 8000,
    joinedAt: '2023-01-20',
    deliveryRoute: 'Route C',
  },
  {
    id: 'c4',
    name: 'Maison Café Group',
    email: 'ops@maisoncafe.com',
    phone: '+1 (555) 567-8901',
    address: '200 Oak Boulevard',
    city: 'San Francisco, CA',
    accountNumber: 'ACC-0045',
    status: 'active',
    balance: 12450.0,
    creditLimit: 30000,
    joinedAt: '2020-07-08',
    deliveryRoute: 'Route A',
  },
  {
    id: 'c5',
    name: 'Petite Épicerie',
    email: 'hello@petiteepicerie.com',
    phone: '+1 (555) 678-9012',
    address: '77 Church Street',
    city: 'Boston, MA',
    accountNumber: 'ACC-0046',
    status: 'inactive',
    balance: 0,
    creditLimit: 5000,
    joinedAt: '2022-09-14',
    deliveryRoute: 'Route D',
  },
];

export const mockItems: Item[] = [
  { id: 'i1', sku: 'BRD-001', name: 'Pain de Campagne 800g', category: 'Sourdough', unit: 'loaf', unitPrice: 8.5, cost: 2.8, stock: 240, isActive: true },
  { id: 'i2', sku: 'VIE-001', name: 'Croissant au Beurre', category: 'Viennoiserie', unit: 'piece', unitPrice: 4.25, cost: 1.2, stock: 480, isActive: true },
  { id: 'i3', sku: 'BRD-002', name: 'Pane di Altamura 1kg', category: 'Artisan Loaves', unit: 'loaf', unitPrice: 9.0, cost: 3.1, stock: 120, isActive: true },
  { id: 'i4', sku: 'FLT-001', name: 'Focaccia Genovese 600g', category: 'Flatbreads', unit: 'piece', unitPrice: 6.75, cost: 2.1, stock: 180, isActive: true },
  { id: 'i5', sku: 'BAG-001', name: 'Baguette Tradition', category: 'Baguettes', unit: 'piece', unitPrice: 3.5, cost: 0.9, stock: 600, isActive: true },
];

export const mockOrders: Order[] = [
  {
    id: 'o1',
    orderNumber: 'ORD-2024-0891',
    customerId: 'c1',
    customerName: 'Le Jardin Restaurant',
    status: 'delivered',
    lines: [
      { id: 'ol1', itemId: 'i1', itemName: 'Pain de Campagne 800g', sku: 'BRD-001', quantity: 12, unitPrice: 8.5, total: 102 },
      { id: 'ol2', itemId: 'i5', itemName: 'Baguette Tradition', sku: 'BAG-001', quantity: 24, unitPrice: 3.5, total: 84 },
    ],
    total: 186,
    deliveryDate: '2024-12-16',
    createdAt: '2024-12-15',
    route: 'Route A',
  },
  {
    id: 'o2',
    orderNumber: 'ORD-2024-0892',
    customerId: 'c2',
    customerName: 'The Granary Hotel',
    status: 'in_production',
    lines: [
      { id: 'ol3', itemId: 'i2', itemName: 'Croissant au Beurre', sku: 'VIE-001', quantity: 60, unitPrice: 4.25, total: 255 },
      { id: 'ol4', itemId: 'i3', itemName: 'Pane di Altamura 1kg', sku: 'BRD-002', quantity: 8, unitPrice: 9.0, total: 72 },
    ],
    total: 327,
    deliveryDate: '2024-12-17',
    createdAt: '2024-12-15',
    route: 'Route B',
  },
  {
    id: 'o3',
    orderNumber: 'ORD-2024-0893',
    customerId: 'c3',
    customerName: 'Bistro Vieux Carré',
    status: 'confirmed',
    lines: [
      { id: 'ol5', itemId: 'i4', itemName: 'Focaccia Genovese 600g', sku: 'FLT-001', quantity: 15, unitPrice: 6.75, total: 101.25 },
      { id: 'ol6', itemId: 'i5', itemName: 'Baguette Tradition', sku: 'BAG-001', quantity: 30, unitPrice: 3.5, total: 105 },
    ],
    total: 206.25,
    deliveryDate: '2024-12-18',
    createdAt: '2024-12-16',
    route: 'Route C',
  },
  {
    id: 'o4',
    orderNumber: 'ORD-2024-0894',
    customerId: 'c4',
    customerName: 'Maison Café Group',
    status: 'pending',
    lines: [
      { id: 'ol7', itemId: 'i1', itemName: 'Pain de Campagne 800g', sku: 'BRD-001', quantity: 20, unitPrice: 8.5, total: 170 },
      { id: 'ol8', itemId: 'i2', itemName: 'Croissant au Beurre', sku: 'VIE-001', quantity: 48, unitPrice: 4.25, total: 204 },
    ],
    total: 374,
    deliveryDate: '2024-12-19',
    createdAt: '2024-12-16',
    route: 'Route A',
  },
  {
    id: 'o5',
    orderNumber: 'ORD-2024-0895',
    customerId: 'c1',
    customerName: 'Le Jardin Restaurant',
    status: 'dispatched',
    lines: [
      { id: 'ol9', itemId: 'i3', itemName: 'Pane di Altamura 1kg', sku: 'BRD-002', quantity: 6, unitPrice: 9.0, total: 54 },
    ],
    total: 54,
    deliveryDate: '2024-12-17',
    createdAt: '2024-12-16',
    route: 'Route A',
  },
];

export const mockInvoices: Invoice[] = [
  {
    id: 'inv1',
    invoiceNumber: 'INV-2024-1201',
    customerId: 'c1',
    customerName: 'Le Jardin Restaurant',
    orderId: 'o1',
    orderNumber: 'ORD-2024-0891',
    amount: 186,
    balance: 186,
    status: 'open',
    issuedAt: '2024-12-16',
    dueAt: '2024-12-30',
  },
  {
    id: 'inv2',
    invoiceNumber: 'INV-2024-1198',
    customerId: 'c2',
    customerName: 'The Granary Hotel',
    orderId: 'o2',
    orderNumber: 'ORD-2024-0888',
    amount: 1250,
    balance: 625,
    status: 'partial',
    issuedAt: '2024-12-10',
    dueAt: '2024-12-24',
  },
  {
    id: 'inv3',
    invoiceNumber: 'INV-2024-1185',
    customerId: 'c4',
    customerName: 'Maison Café Group',
    orderId: 'o4',
    orderNumber: 'ORD-2024-0875',
    amount: 3400,
    balance: 3400,
    status: 'overdue',
    issuedAt: '2024-11-28',
    dueAt: '2024-12-12',
  },
];

export const mockPayments: Payment[] = [
  {
    id: 'pay1',
    paymentNumber: 'PAY-2024-0445',
    customerId: 'c2',
    customerName: 'The Granary Hotel',
    invoiceId: 'inv2',
    amount: 625,
    method: 'bank_transfer',
    reference: 'BANK-REF-77821',
    paidAt: '2024-12-14',
  },
  {
    id: 'pay2',
    paymentNumber: 'PAY-2024-0446',
    customerId: 'c3',
    customerName: 'Bistro Vieux Carré',
    amount: 890.25,
    method: 'credit_card',
    reference: 'CC-TXN-99210',
    paidAt: '2024-12-15',
  },
];

export const mockTenantMetrics: TenantDashboardMetrics = {
  totalRevenue: {
    label: 'Revenue This Month',
    value: 48620,
    change: 12.4,
    changeLabel: 'vs last month',
    prefix: '$',
  },
  totalOrders: {
    label: "Today's Orders",
    value: 47,
    change: 8.2,
    changeLabel: 'vs yesterday',
  },
  activeCustomers: {
    label: 'Active Customers',
    value: 134,
    change: 3.1,
    changeLabel: 'vs last month',
  },
  productionToday: {
    label: 'Units in Production',
    value: 1840,
    change: -2.4,
    changeLabel: 'vs yesterday',
  },
  outstandingAR: {
    label: 'Outstanding AR',
    value: 21340,
    change: -5.8,
    changeLabel: 'vs last week',
    prefix: '$',
  },
  avgOrderValue: {
    label: 'Avg Order Value',
    value: 284,
    change: 4.7,
    changeLabel: 'vs last month',
    prefix: '$',
  },
};

export const mockCustomerMetrics: CustomerDashboardMetrics = {
  totalOrders: {
    label: 'Total Orders',
    value: 48,
    change: 6.3,
    changeLabel: 'vs last month',
  },
  openInvoices: {
    label: 'Open Invoices',
    value: 3,
  },
  lastOrderDate: {
    label: 'Last Order',
    value: 'Dec 16, 2024',
  },
  outstandingBalance: {
    label: 'Outstanding Balance',
    value: 2340.5,
    prefix: '$',
  },
};
