-- ============================================================
-- BPS_ITEMS — REMOVED
--
-- All columns formerly in bps_items have been merged into fnd_items.
-- This file is kept for git history only. It has no effect.
--
-- Migration applied: merge_bps_items_into_fnd_items
-- ============================================================
